---
version: "3.8"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - "d:/docker/appdata/sonarr:/config"
      - "d:/shared:/data"
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent:release
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Manila
    volumes:
      - "d:/docker/appdata/qbittorrent:/config"
      - "d:/shared/torrents:/data/torrents"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - "d:/docker/appdata/prowlarr:/config"
    ports:
      - 9696:9696
    restart: unless-stopped
