---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /home/user/appdata/sonarr:/config
      - "D:/Downloads:/downloads"
      - "D:/Shared/Kodi/TV Shows:/tv"
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - WEBUI_PORT=8080
    volumes:
      - /home/user/appdata/qbittorrent:/config
      - "D:/Downloads:/downloads"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /home/user/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
