---
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DEFAULT_VOLUME}/${APP_DATA}/watchtower/config.json:/config.json
    command: jellyfin radarr sonarr prowlarr qbittorrent
    environment:
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM = watchtower@skullpluggery.io
      - WATCHTOWER_NOTIFICATION_EMAIL_TO = ${EMAIL_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER = smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT = 587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER = ${EMAIL_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD = ${EMAIL_PASSWORD}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY = 30
      - WATCHTOWER_NOTIFICATIONS = email

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 8096:8096
    group_add:
      - "110"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/jellyfin:/config
      - ${DEFAULT_VOLUME}/${DATA}/media:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/radarr:/config
      - ${DEFAULT_VOLUME}/${DATA}:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/sonarr:/config
      - ${DEFAULT_VOLUME}/${DATA}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent:release
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Manila
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/qbittorrent:/config
      - ${DEFAULT_VOLUME}/${DATA}/torrents:/data/torrents
    restart: unless-stopped
